'use client'

import { useMemo, useState } from 'react'
import { M31_GRIEVANCES, M31_TIMELINE } from '@/data/fixtures/data'

type Grievance = typeof M31_GRIEVANCES[number]
type Filter = 'all' | 'Open' | 'Escalated' | 'Resolved'

const statusStyles: Record<string, string> = {
  'SLA Breach': 'bg-red-50 text-red-700 border-red-200',
  Open: 'bg-amber-50 text-amber-700 border-amber-200',
  Escalated: 'bg-purple-50 text-purple-700 border-purple-200',
  Resolved: 'bg-emerald-50 text-emerald-700 border-emerald-200',
}

function StatusBadge({ status }: { status: string }) {
  return <span className={`rounded border px-2 py-0.5 text-[10px] font-bold ${statusStyles[status] ?? 'border-slate-200 bg-slate-50 text-slate-700'}`}>{status}</span>
}

export function M31GrievanceWorkspace({ onBack, onOpenApp, onOpenSLA, onOpenQuery, onOpenInspection, onOpenRegAssistant }: {
  onBack: () => void
  onOpenApp: (applicationId: string) => void
  onOpenSLA: () => void
  onOpenQuery: (applicationId: string) => void
  onOpenInspection: (applicationId: string, inspectionId: string) => void
  onOpenRegAssistant?: () => void
}) {
  const [filter, setFilter] = useState<Filter>('all')
  const [lang, setLang] = useState<'en' | 'mr'>('en')
  const [selectedId, setSelectedId] = useState(M31_GRIEVANCES[0].id)
  const [resolutionType, setResolutionType] = useState('')
  const [applicationAction, setApplicationAction] = useState('No change to application')
  const [resolutionText, setResolutionText] = useState('')
  const [resolved, setResolved] = useState(false)
  const selected = M31_GRIEVANCES.find(grievance => grievance.id === selectedId) ?? M31_GRIEVANCES[0]
  const grievances = useMemo(() => filter === 'all' ? M31_GRIEVANCES : M31_GRIEVANCES.filter(grievance => grievance.status === filter), [filter])

  const openEvidence = (label: string) => {
    if (label === 'Application Documents' || label === 'Scrutiny Findings') onOpenApp(selected.appId)
    else if (label === 'Queries / Responses') onOpenQuery(selected.appId)
    else if (label === 'Inspection Records') onOpenInspection(selected.appId, 'INSP-2026-00388')
    else if (label === 'SLA Record') onOpenSLA()
  }

  return <main className="flex-1 overflow-y-auto bg-[#f8f9fb]"><style jsx>{`@media (min-width: 1024px) { [data-section="routing"], [data-section="regulatory"] { display: none; } }`}</style>
    <div className="mx-auto max-w-[1480px] px-6 py-5">
      <nav className="mb-3 flex items-center gap-2 text-xs text-[#374151]" aria-label="Breadcrumb"><button onClick={onBack} className="hover:text-[#1a3a5c] hover:underline">Department Home</button><span>›</span><span>SLA &amp; Escalations</span><span>›</span><span className="font-semibold text-[#1a3a5c]">Escalation / Grievance</span></nav>
      <header className="mb-5 flex items-start justify-between gap-4"><div><h1 className="text-2xl font-bold text-[#1a3a5c]">Escalation / Grievance</h1><p className="mt-1 text-sm text-[#1a2533]">Review escalated issues, evidence, routing, and take resolution action.</p></div><div className="flex items-center gap-3"><div className="flex rounded-lg bg-[#eef3f8] p-1" aria-label="Language"><button onClick={() => setLang('en')} className={`rounded-md px-4 py-2 text-sm font-semibold ${lang === 'en' ? 'bg-[#dbeafe] text-[#1559c5]' : 'text-[#173b64]'}`}>English</button><button onClick={() => setLang('mr')} className={`rounded-md px-4 py-2 text-sm font-semibold ${lang === 'mr' ? 'bg-[#dbeafe] text-[#1559c5]' : 'text-[#173b64]'}`}>मराठी</button></div><button onClick={onBack} className="rounded border border-[#cbd5e1] bg-white px-4 py-2 text-sm text-[#1a2533] hover:bg-[#f8fafc]">← Back</button></div></header>

      <div className="grid items-start gap-5 lg:grid-cols-[290px_minmax(0,1fr)_350px]">
        <aside aria-label="Active grievances" className="rounded-lg border border-[#dce5ef] bg-white p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-base font-bold text-[#173b64]">Grievances</h2><span className="text-xs text-[#64748b]">{grievances.length}</span></div><input aria-label="Search grievances" placeholder="Search by GRV no., applicant or reason…" className="mb-3 w-full rounded border border-[#d8e1eb] px-3 py-2 text-xs outline-none focus:border-[#1a56db]" /><div className="mb-3 flex flex-wrap gap-1.5">{(['all', 'Open', 'Escalated', 'Resolved'] as Filter[]).map(value => <button key={value} onClick={() => setFilter(value)} className={`rounded-lg border px-2.5 py-1.5 text-xs font-semibold ${filter === value ? 'border-[#bfdbfe] bg-[#eaf2ff] text-[#1559c5]' : 'border-[#d8e1eb] bg-white text-[#52657d] hover:border-[#8bb8f0]'}`}>{value === 'all' ? 'All' : value}</button>)}</div><div className="space-y-2">{grievances.map(grievance => <button key={grievance.id} onClick={() => { setSelectedId(grievance.id); setResolved(false) }} className={`w-full rounded-lg border p-3 text-left transition-colors ${selected.id === grievance.id ? 'border-[#1a56db] bg-[#eff6ff] ring-1 ring-[#1a56db]' : 'border-[#dce5ef] bg-white hover:border-[#8bb8f0]'}`}><div className="flex items-start justify-between gap-2"><span className="text-xs font-bold text-[#173b64]">{grievance.id}</span><StatusBadge status={grievance.status} /></div><p className="mt-2 text-xs font-semibold text-[#1a2533]">{grievance.business}</p><p className="mt-1 text-[11px] text-[#52657d]">{grievance.appId} · MIDC {grievance.service}</p><p className="mt-1 text-[11px] text-[#52657d]">{grievance.reason}</p><p className="mt-1 text-[11px] text-[#52657d]">{grievance.raised}</p></button>)}</div></aside>

        <section className="space-y-4" aria-label="Selected grievance case">
          <section className="rounded-lg border border-[#dce5ef] bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className="text-sm font-bold text-[#173b64]">{selected.id}</span><StatusBadge status={resolved ? 'Resolved' : selected.reason} /></div><p className="mt-2 text-base font-bold text-[#1a2533]">{selected.business}</p><button onClick={() => onOpenApp(selected.appId)} className="mt-0.5 text-sm font-semibold text-[#1559c5] hover:underline">{selected.appId} · MIDC {selected.service} →</button></div><div className="text-right text-xs text-[#52657d]"><p>Raised by: <strong className="text-[#1a2533]">{selected.raisedBy}</strong></p><p className="mt-1">{selected.raised}</p></div></div><dl className="mt-4 grid gap-3 border-t border-[#edf2f7] pt-3 text-xs sm:grid-cols-3 lg:grid-cols-5"><div><dt className="text-[#64748b]">Reason</dt><dd className="mt-1 font-semibold text-[#1a2533]">{selected.reason}</dd></div><div><dt className="text-[#64748b]">Assigned desk</dt><dd className="mt-1 font-semibold text-[#1a2533]">{selected.assignedDesk}</dd></div><div><dt className="text-[#64748b]">Assigned role</dt><dd className="mt-1 font-semibold text-[#1a2533]">{selected.assignedRole}</dd></div><div><dt className="text-[#64748b]">Raised by</dt><dd className="mt-1 font-semibold text-[#1a2533]">{selected.raisedBy}</dd></div><div><dt className="text-[#64748b]">Raised on</dt><dd className="mt-1 font-semibold text-[#1a2533]">{selected.raised}</dd></div></dl></section>

          {selected.reason === 'SLA Breach' && <section className="rounded-lg border border-red-200 bg-red-50 p-4"><h2 className="text-xs font-bold uppercase tracking-wider text-red-700">SLA breach context</h2><div className="mt-3 grid gap-3 text-xs sm:grid-cols-3"><div><p className="text-red-600">Configured SLA</p><p className="mt-1 font-bold text-red-800">{selected.configuredSla}</p></div><div><p className="text-red-600">Actual elapsed</p><p className="mt-1 font-bold text-red-800">{selected.actualElapsed}</p></div><div><p className="text-red-600">Exceeded by</p><p className="mt-1 font-bold text-red-800">{selected.slaExceededBy}</p></div></div><button onClick={onOpenSLA} className="mt-3 rounded border border-red-300 bg-white px-3 py-1.5 text-xs font-semibold text-red-700 hover:bg-red-100">View SLA Breakdown →</button></section>}
          {selected.reason === 'Inspection Delay' && <section className="rounded-lg border border-amber-200 bg-amber-50 p-4"><h2 className="text-xs font-bold uppercase tracking-wider text-amber-700">Inspection delay context</h2><div className="mt-3 grid gap-3 text-xs sm:grid-cols-3"><div><p className="text-amber-700">Inspection ID</p><p className="mt-1 font-bold">INSP-2026-00388</p></div><div><p className="text-amber-700">Required</p><p className="mt-1 font-bold">15 Sep 2026</p></div><div><p className="text-amber-700">Status</p><p className="mt-1 font-bold text-amber-800">Pending · 8 days</p></div></div><button onClick={() => onOpenInspection(selected.appId, 'INSP-2026-00388')} className="mt-3 rounded border border-amber-300 bg-white px-3 py-1.5 text-xs font-semibold text-amber-700 hover:bg-amber-100">View Inspection →</button></section>}

          <section className="rounded-lg border border-[#dce5ef] bg-white p-4"><h2 className="text-xs font-bold uppercase tracking-wider text-[#173b64]">Application evidence timeline</h2><div className="mt-4 space-y-2">{M31_TIMELINE.map((event, index) => { const dot = event.type === 'breach' ? 'bg-red-500' : event.type === 'grievance' ? 'bg-purple-500' : event.type === 'sla' ? 'bg-amber-500' : event.type === 'query' ? 'bg-blue-500' : 'bg-[#cbd5e1]'; const action = event.link === 'M30' ? onOpenSLA : event.link === 'M18' ? () => onOpenQuery(selected.appId) : event.link ? () => onOpenApp(selected.appId) : undefined; return <div key={`${event.date}-${event.event}`} className="flex gap-3"><div className="flex w-2.5 shrink-0 flex-col items-center"><span className={`mt-1.5 h-2.5 w-2.5 rounded-full ${dot}`} />{index < M31_TIMELINE.length - 1 && <span className="mt-1 h-6 w-px bg-[#e2e8f0]" />}</div><div className="flex flex-wrap gap-x-2 gap-y-1 pb-1 text-sm"><span className="text-[#52657d]">{event.date}</span><span className="text-[#1a2533]">{event.event}</span>{action && <button onClick={action} className="font-semibold text-[#1559c5] hover:underline">View workflow →</button>}</div></div> })}</div></section>

          <section data-section="routing" className="rounded-lg border border-[#dce5ef] bg-white p-4"><h2 className="text-xs font-bold uppercase tracking-wider text-[#173b64]">Escalation routing</h2><div className="mt-4 flex flex-wrap items-center gap-2 text-xs">{[{ label: 'Problem raised', sub: selected.raisedBy, color: 'bg-slate-50' }, { label: selected.assignedDesk, sub: selected.assignedRole, color: 'bg-amber-50' }, { label: selected.status === 'Escalated' ? 'Nodal Officer' : 'Under review', sub: selected.status === 'Escalated' ? 'Configured level' : 'Assigned desk', color: selected.status === 'Escalated' ? 'bg-purple-50' : 'bg-slate-50' }, { label: resolved || selected.status === 'Resolved' ? 'Resolved' : 'Resolution pending', sub: '', color: 'bg-slate-50' }].map((step, index, steps) => <div key={step.label} className="flex items-center gap-2"><div className={`min-w-[116px] rounded border border-[#dce5ef] px-3 py-2 text-center ${step.color}`}><p className="font-semibold text-[#1a2533]">{step.label}</p>{step.sub && <p className="mt-0.5 text-[10px] text-[#64748b]">{step.sub}</p>}</div>{index < steps.length - 1 && <span className="text-[#64748b]">→</span>}</div>)}</div></section>

          <section className="rounded-lg border border-[#dce5ef] bg-white p-4"><h2 className="text-xs font-bold uppercase tracking-wider text-[#173b64]">Evidence</h2><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{['Application Documents', 'Scrutiny Findings', 'Queries / Responses', 'Inspection Records', 'SLA Record', 'Other Supporting Evidence'].map(label => <button key={label} onClick={() => openEvidence(label)} className="flex items-center justify-between rounded border border-[#e2e8f0] px-3 py-2.5 text-left text-xs font-semibold text-[#294d78] hover:border-[#8bb8f0] hover:bg-[#f8fbff]">{label}<span>View →</span></button>)}</div></section>

          <section data-section="regulatory" className="rounded-lg border border-[#dce5ef] bg-white p-4"><div className="flex items-center justify-between gap-3"><h2 className="text-xs font-bold uppercase tracking-wider text-[#173b64]">Regulatory context</h2>{onOpenRegAssistant && <button onClick={onOpenRegAssistant} className="text-xs font-semibold text-[#1559c5] hover:underline">View full regulation →</button>}</div><p className="mt-3 text-sm font-semibold text-[#1a2533]">MIDC Building Regulations 2019</p><p className="mt-1 text-xs text-[#52657d]">Clause 4.3.2 — Built-up Area Calculation</p><p className="mt-3 rounded bg-[#fff9df] px-3 py-2 text-xs leading-relaxed text-[#384b62]">The built-up area shall be calculated in accordance with the provisions in this section for determining permissible FSI and compliance with building controls.</p></section>

          <section className="rounded-lg border border-[#dce5ef] bg-white p-4"><h2 className="text-xs font-bold uppercase tracking-wider text-[#173b64]">Resolution workspace</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-xs text-[#52657d]">Resolution type<select value={resolutionType} onChange={event => setResolutionType(event.target.value)} className="mt-1.5 w-full rounded border border-[#cbd5e1] bg-white px-3 py-2.5 text-sm text-[#1a2533]"><option value="">Select type</option><option>Resolved</option><option>Information Provided</option><option>Action Taken</option><option>Forwarded to Relevant Desk</option><option>Awaiting Applicant Action</option><option>Escalated Further</option></select></label><label className="text-xs text-[#52657d]">Related application action<select value={applicationAction} onChange={event => setApplicationAction(event.target.value)} className="mt-1.5 w-full rounded border border-[#cbd5e1] bg-white px-3 py-2.5 text-sm text-[#1a2533]"><option>No change to application</option><option>Application review required</option><option>Query follow-up required</option><option>SLA escalation recorded</option></select></label></div><label className="mt-3 block text-xs text-[#52657d]">Resolution explanation<textarea value={resolutionText} onChange={event => setResolutionText(event.target.value)} rows={3} placeholder="Enter resolution explanation and action taken…" className="mt-1.5 w-full resize-none rounded border border-[#cbd5e1] px-3 py-2.5 text-sm text-[#1a2533] outline-none focus:border-[#1a56db] focus:ring-2 focus:ring-[#bfdbfe]" /></label><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => setResolved(true)} disabled={!resolutionType || !resolutionText.trim()} className="rounded bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-800 disabled:cursor-not-allowed disabled:opacity-40">Record Resolution</button><button onClick={() => alert('Grievance escalated to Tier-2 Appellate Authority. Dispatch ref: ESC-2026-0012.')} className="rounded border border-purple-200 bg-purple-50 px-4 py-2.5 text-sm font-semibold text-purple-700 hover:bg-purple-100">Escalate Further</button><button onClick={() => onOpenApp(selected.appId)} className="rounded border border-[#cbd5e1] bg-white px-4 py-2.5 text-sm font-semibold text-[#294d78] hover:bg-[#f8fafc]">Open Application</button></div>{resolved && <p className="mt-3 rounded border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-700">Resolution recorded. Grievance marked as Resolved.</p>}</section>
        </section>
        <aside className="hidden space-y-4 lg:block" aria-label="Case context">
          <section className="rounded-xl border border-[#dce5ef] bg-white p-5 shadow-sm"><h2 className="text-base font-bold text-[#173b64]">Escalation Routing</h2><div className="mt-5 space-y-3">{[{ label: 'Problem Raised', sub: selected.raisedBy, color: 'bg-emerald-50 border-emerald-200' }, { label: selected.assignedDesk, sub: selected.assignedRole, color: 'bg-emerald-50 border-emerald-200' }, { label: selected.status === 'Escalated' ? 'Nodal Officer' : 'Under Review', sub: selected.status === 'Escalated' ? 'Configured Level' : 'Assigned Desk', color: 'bg-blue-50 border-blue-200' }, { label: resolved || selected.status === 'Resolved' ? 'Resolved' : 'Resolution Pending', sub: '', color: 'bg-slate-50 border-slate-200' }].map((step, index, steps) => <div key={step.label} className="flex items-center gap-2"><div className={`flex-1 rounded-lg border px-3 py-3 text-center ${step.color}`}><p className="text-sm font-semibold text-[#173b64]">{step.label}</p>{step.sub && <p className="mt-1 text-xs text-[#64748b]">{step.sub}</p>}</div>{index < steps.length - 1 && <span className="text-lg text-[#64748b]">→</span>}</div>)}</div></section>
          <section className="rounded-xl border border-[#dce5ef] bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><h2 className="text-base font-bold text-[#173b64]">Regulatory Context</h2>{onOpenRegAssistant && <button onClick={onOpenRegAssistant} className="text-xs font-semibold text-[#1559c5] hover:underline">Open →</button>}</div><div className="mt-4 rounded-lg bg-[#eef6ff] p-4"><p className="text-sm font-bold text-[#173b64]">MIDC Building Regulations 2019</p><p className="mt-1 text-xs text-[#52657d]">Clause 4.3.2 — Built-up Area Calculation</p></div><p className="mt-4 text-sm leading-relaxed text-[#384b62]">The built-up area shall be calculated in accordance with this section for determining permissible FSI and compliance with building controls.</p>{onOpenRegAssistant && <button onClick={onOpenRegAssistant} className="mt-4 text-sm font-semibold text-[#1559c5] hover:underline">View full regulation →</button>}</section>
        </aside>
      </div>
    </div>
  </main>
}
