import React from 'react';
import { findBusinessEntity } from '../identity/catalog';

export type DocReqState = 'Required' | 'Conditional' | 'Not Required';
export type DocAvailState = 'Missing' | 'Uploaded' | 'Processing' | 'Available';
export type DocVerifState =
  | 'Self-declared'
  | 'User-confirmed'
  | 'System-verified'
  | 'Department-verified'
  | 'Needs Verification'
  | 'Invalid'
  | 'Government-issued';
export type DocValidity = 'Valid' | 'Expired' | 'Not Applicable';
export type DocReuse = 'Reusable' | 'Service-specific';
export type DocDependency =
  | 'Available now'
  | 'Generated by prerequisite approval'
  | 'Blocked until prerequisite'
  | 'Inspection-stage only'
  | 'Unlocks downstream services';

export interface ExtractedInfo {
  fields: { label: string; value: string; match?: boolean }[];
  verificationState: string;
  reviewRequired: boolean;
  summary?: string;
}

export interface CertificateInfo {
  certNumber: string;
  authority: string;
  issueDate: string;
  validUntil: string;
  signatoryName: string;
  designation: string;
  qrPayload: string;
  conditions: string[];
}

export interface DocRecord {
  id: string;
  name: string;
  category: string;
  issueDate: string;
  expiryDate: string;
  source: string;
  requirement: DocReqState;
  availability: DocAvailState;
  verification: DocVerifState;
  validity: DocValidity;
  reuse: DocReuse;
  dependency: DocDependency;
  usedBy: { dept: string; service: string; requirement: string }[];
  version: number;
  description: string;
  whyRequired: string;
  whatItContains: string;
  grRule: string | null;
  grClause: string | null;
  grEffective: string | null;
  whereObtained: string;
  versionHistory: { version: number; uploaded: string; verification: string }[];
  triggeringCondition?: string;
  extractedData?: ExtractedInfo;
  certificateData?: CertificateInfo;
}

export const EKATMA_DOCS: readonly DocRecord[] = [
  {
    id: 'DOC-001',
    name: 'Project Environmental Report / DPR',
    category: 'Environmental',
    issueDate: '12 Sep 2026',
    expiryDate: '—',
    source: 'Applicant / Consultant',
    requirement: 'Required',
    availability: 'Available',
    verification: 'Needs Verification',
    validity: 'Valid',
    reuse: 'Service-specific',
    dependency: 'Available now',
    usedBy: [
      { dept: 'MPCB', service: 'Consent to Establish', requirement: 'Required' },
      { dept: 'DISH', service: 'Factory Registration', requirement: 'Supporting document' },
    ],
    version: 3,
    description: 'A comprehensive project report covering environmental impact, effluent treatment, emission management, and operational processes for the proposed industrial unit.',
    whyRequired: 'Regulatory authorities require a detailed project report to assess the environmental footprint of the proposed project before granting consent.',
    whatItContains: 'Project description, production process, pollution control measures, ETP design details, air emission inventory, hazardous waste management plan.',
    grRule: 'Maharashtra Prevention and Control of Pollution Rules',
    grClause: 'Rule 5 — Consent to Establish',
    grEffective: '01 Jan 2000',
    whereObtained: 'Prepared by a qualified environmental consultant or the applicant. Must be signed by the authorised signatory.',
    versionHistory: [
      { version: 3, uploaded: '12 Sep 2026', verification: 'Needs Verification' },
      { version: 2, uploaded: '04 Aug 2026', verification: 'Self-declared' },
      { version: 1, uploaded: '20 Jul 2026', verification: 'Self-declared' },
    ],
    extractedData: {
      fields: [
        { label: 'Unit Capacity', value: '50,000 MT/year Bulk Drugs', match: true },
        { label: 'Daily Water Consumption', value: '85 KLD (Fresh MIDC Supply)', match: true },
        { label: 'Industrial Wastewater', value: '55 KLD', match: true },
        { label: 'Hazardous Waste', value: 'Category 28.1 (Chemical Sludge - 12 MT/yr)', match: false },
      ],
      verificationState: 'Needs Verification',
      reviewRequired: true,
      summary: 'Hazardous waste quantification requires minor confirmation against initial profile estimate (12 MT vs 10 MT).',
    },
  },
  {
    id: 'DOC-002',
    name: 'Land Possession / MIDC Lease Agreement',
    category: 'Land',
    issueDate: '15 Jun 2026',
    expiryDate: '14 Jun 2086',
    source: 'MIDC',
    requirement: 'Required',
    availability: 'Available',
    verification: 'User-confirmed',
    validity: 'Valid',
    reuse: 'Reusable',
    dependency: 'Available now',
    usedBy: [
      { dept: 'MPCB', service: 'Consent to Establish', requirement: 'Required' },
      { dept: 'Fire', service: 'NOC Application', requirement: 'Required' },
      { dept: 'DISH', service: 'Factory Registration', requirement: 'Required' },
      { dept: 'MIDC', service: 'Plot Possession', requirement: 'Primary document' },
    ],
    version: 1,
    description: "MIDC allotment letter, possession receipt, and lease agreement confirming the applicant's legal right to occupy and use the industrial plot.",
    whyRequired: 'Proof of legal land possession is a prerequisite for all departmental approvals related to construction and operation of the industrial unit.',
    whatItContains: 'Allotment order, plot number, area, lease period, possession date, lessee and lessor details, applicable terms and conditions.',
    grRule: 'MIDC Act 1961',
    grClause: 'Section 32 — Industrial Land Allotment',
    grEffective: '01 Apr 1962',
    whereObtained: 'Issued by MIDC Estate Office after allotment and payment of applicable charges. Original documents provided at time of plot possession.',
    versionHistory: [
      { version: 1, uploaded: '20 Jun 2026', verification: 'User-confirmed' },
    ],
    extractedData: {
      fields: [
        { label: 'Allottee Name', value: 'Sahyadri Bio-Pharma Private Limited', match: true },
        { label: 'Plot Designation', value: 'Plot No. E-24, Phase II, MIDC Thane', match: true },
        { label: 'Plot Area', value: '12,500 sq. meters', match: true },
        { label: 'Lease Tenure', value: '95 Years (to 14 Jun 2086)', match: true },
        { label: 'Issuing Authority', value: 'MIDC Regional Office, Thane Division', match: true },
      ],
      verificationState: 'Verified against Land Registry',
      reviewRequired: false,
      summary: 'Land allotment and coordinates cross-referenced and verified with MIDC Land Desk.',
    },
    certificateData: {
      certNumber: 'MIDC/ALLOT/THN/2026/0482',
      authority: 'Maharashtra Industrial Development Corporation (MIDC)',
      issueDate: '15 Jun 2026',
      validUntil: '14 Jun 2086',
      signatoryName: 'Shri R. K. Gaikwad',
      designation: 'Area Manager & Estate Officer, MIDC Thane Division',
      qrPayload: 'https://maitri.mahaonline.gov.in/verify/land?ref=MIDC-ALLOT-THN-2026-0482',
      conditions: [
        'Plot allotted exclusively for pharmaceutical / chemical manufacturing use.',
        'Possession transferred subject to building plan approval within 180 days.',
        'Ground rent payable annually as per MIDC tariff regulation.',
      ],
    },
  },
  {
    id: 'DOC-003',
    name: 'MPCB Consent to Establish Certificate',
    category: 'Previous Approvals',
    issueDate: '10 Oct 2026',
    expiryDate: '09 Oct 2031',
    source: 'MPCB — Maharashtra Pollution Control Board',
    requirement: 'Conditional',
    availability: 'Available',
    verification: 'Government-issued',
    validity: 'Valid',
    reuse: 'Reusable',
    dependency: 'Unlocks downstream services',
    usedBy: [
      { dept: 'MIDC', service: 'Building / Planning Approval', requirement: 'Prerequisite' },
      { dept: 'Fire', service: 'Provisional Fire NOC', requirement: 'Prerequisite' },
      { dept: 'DISH', service: 'Factory Registration', requirement: 'Required' },
      { dept: 'Boiler', service: 'Boiler Registration', requirement: 'Required' },
    ],
    version: 1,
    description: 'Consent to Establish certificate issued by the Maharashtra Pollution Control Board (MPCB) authorising the establishment of the proposed industrial unit subject to the conditions stated therein. Certificate ID: CERT-CTE-2026-41872. Approval Order: CTE-2026-MPCB-41872.',
    whyRequired: 'The CTE is mandatory for Red Category industries before commencing construction or installation. It confirms that the proposed project meets MPCB environmental norms and approves the pollution control measures proposed.',
    whatItContains: 'Certificate number, approval order reference, approved conditions (ETP capacity ≥ 70 KL/day, stack emission limits, hazardous waste disposal requirements), special conditions, validity period (5 years), and MPCB seal.',
    grRule: 'Maharashtra Prevention and Control of Pollution Rules; Water (Prevention and Control of Pollution) Act 1974; Air (Prevention and Control of Pollution) Act 1981',
    grClause: 'Rule 5 — Consent to Establish',
    grEffective: '01 Jan 2000',
    whereObtained: 'Issued by MPCB upon approval of the Consent to Establish application. Automatically added to the Document Centre when MPCB grants the decision.',
    versionHistory: [
      { version: 1, uploaded: '10 Oct 2026', verification: 'Government-issued' },
    ],
    triggeringCondition: 'Generated automatically when MPCB grants Consent to Establish. Mandatory for all Red Category industries before construction commences.',
    extractedData: {
      fields: [
        { label: 'Category', value: 'Red Category / Large Scale Manufacturing', match: true },
        { label: 'Capital Investment', value: '₹48.50 Crores', match: true },
        { label: 'Approved ETP Capacity', value: '70 KLD Zero Liquid Discharge', match: true },
        { label: 'Air Emission Stacks', value: 'Boiler Stack (30m) & Process Scrubber', match: true },
        { label: 'Order Reference', value: 'MPCB/CTE/RO-THN/2026/7812', match: true },
      ],
      verificationState: 'Government-issued (Digital PKI)',
      reviewRequired: false,
      summary: 'Statutory environmental clearance sanctioned by MPCB Member Secretary.',
    },
    certificateData: {
      certNumber: 'CERT-CTE-2026-41872',
      authority: 'Maharashtra Pollution Control Board (MPCB), Mumbai',
      issueDate: '10 Oct 2026',
      validUntil: '09 Oct 2031',
      signatoryName: 'Dr. V. M. Motghare',
      designation: 'Joint Director (WPC), Maharashtra Pollution Control Board',
      qrPayload: 'https://mpcb.gov.in/verify/consent?cert=CERT-CTE-2026-41872&auth=pki',
      conditions: [
        'Consent valid for establishing manufacturing facility at Plot E-24, MIDC Thane.',
        'Installation of 70 KLD Zero Liquid Discharge ETP mandatory prior to trial operations.',
        'Continuous Online Emission Monitoring System (OCEMS) to be connected to MPCB server.',
        'Separate Consent to Operate (CTO) must be obtained prior to commercial production.',
      ],
    },
  },
  {
    id: 'DOC-004',
    name: 'Building Layout / Architectural Plan',
    category: 'Building',
    issueDate: '—',
    expiryDate: '—',
    source: 'Applicant / Licensed Architect',
    requirement: 'Required',
    availability: 'Missing',
    verification: 'Needs Verification',
    validity: 'Not Applicable',
    reuse: 'Service-specific',
    dependency: 'Available now',
    usedBy: [
      { dept: 'MIDC', service: 'Building Plan Approval', requirement: 'Required' },
      { dept: 'Fire', service: 'NOC Application', requirement: 'Required' },
      { dept: 'DISH', service: 'Factory Registration', requirement: 'Required' },
    ],
    version: 0,
    description: 'Architectural drawings and layout plans of the proposed factory building showing structural details, fire exits, utility areas, and process zones.',
    whyRequired: 'Building authorities and fire departments require approved architectural plans to verify structural safety, fire safety compliance, and adherence to building regulations.',
    whatItContains: 'Floor plans, elevation drawings, sections, fire exit layouts, electrical and utility room details, building dimensions and area statements.',
    grRule: null,
    grClause: null,
    grEffective: null,
    whereObtained: 'Prepared by a licensed architect and submitted to MIDC Estate Office / local building authority for sanction.',
    versionHistory: [],
  },
  {
    id: 'DOC-005',
    name: 'Promoter Identity & KYC Documents',
    category: 'Promoter',
    issueDate: '10 Mar 2024',
    expiryDate: '09 Mar 2034',
    source: 'Government of India',
    requirement: 'Required',
    availability: 'Available',
    verification: 'System-verified',
    validity: 'Valid',
    reuse: 'Reusable',
    dependency: 'Available now',
    usedBy: [
      { dept: 'MPCB', service: 'Consent to Establish', requirement: 'Required' },
      { dept: 'MIDC', service: 'Plot Allotment', requirement: 'Required' },
      { dept: 'DISH', service: 'Factory Registration', requirement: 'Required' },
      { dept: 'Fire', service: 'NOC Application', requirement: 'Required' },
    ],
    version: 2,
    description: 'PAN card, Aadhaar, and authorised signatory declaration for all promoters / directors of the applying entity.',
    whyRequired: 'Identity verification is a prerequisite for all departmental applications to establish legal responsibility for the project.',
    whatItContains: 'PAN card copies, Aadhaar card copies, authorised signatory board resolution or power of attorney.',
    grRule: 'Prevention of Money Laundering Act, 2002',
    grClause: 'KYC Verification Requirements',
    grEffective: '01 Jul 2005',
    whereObtained: 'Issued by Government of India. Self-uploaded by the promoter / authorised representative.',
    versionHistory: [
      { version: 2, uploaded: '15 Aug 2026', verification: 'System-verified' },
      { version: 1, uploaded: '10 Mar 2024', verification: 'Self-declared' },
    ],
    extractedData: {
      fields: [
        { label: 'Director Identification (DIN)', value: '08492014', match: true },
        { label: 'Permanent Account (PAN)', value: 'AAECS4821P', match: true },
        { label: 'Authorised Signatory', value: 'Vikramaditya Shinde', match: true },
        { label: 'Designation', value: 'Managing Director', match: true },
      ],
      verificationState: 'System-verified (MCA & CBDT API)',
      reviewRequired: false,
      summary: 'Signatory authority cross-referenced and validated with MCA21 company master.',
    },
  },
  {
    id: 'DOC-006',
    name: 'Effluent Treatment Plant Design Details',
    category: 'Technical',
    issueDate: '08 Sep 2026',
    expiryDate: '—',
    source: 'Applicant / Technical Consultant',
    requirement: 'Required',
    availability: 'Uploaded',
    verification: 'Needs Verification',
    validity: 'Valid',
    reuse: 'Service-specific',
    dependency: 'Available now',
    usedBy: [
      { dept: 'MPCB', service: 'Consent to Establish', requirement: 'Required' },
    ],
    version: 1,
    description: 'Technical design and specifications for the proposed Zero Liquid Discharge (ZLD) Effluent Treatment Plant including treatment process flow, capacity, and equipment details.',
    whyRequired: 'MPCB requires ETP design details to verify that the proposed plant can adequately treat industrial effluent before consent is granted.',
    whatItContains: 'Process flow diagram, treatment capacity, equipment list, mass balance, operating parameters, ZLD discharge schedule.',
    grRule: 'Maharashtra Prevention and Control of Pollution Rules',
    grClause: 'Schedule I — Effluent Standards',
    grEffective: '01 Jan 2000',
    whereObtained: 'Designed by a qualified environmental engineer or process consultant. To be certified by a registered consultant.',
    versionHistory: [
      { version: 1, uploaded: '08 Sep 2026', verification: 'Needs Verification' },
    ],
    extractedData: {
      fields: [
        { label: 'Design Capacity', value: '70 KLD', match: true },
        { label: 'Technology', value: 'Primary, Secondary Biological & RO + MEE', match: true },
        { label: 'Zero Liquid Discharge', value: '100% Recycled for Cooling / Steam', match: true },
      ],
      verificationState: 'Needs Verification',
      reviewRequired: false,
      summary: 'Technical specs extracted from engineering drawings; pending board engineer review.',
    },
  },
  {
    id: 'DOC-007',
    name: 'Applicant Declaration — Accuracy of Information',
    category: 'Declarations',
    issueDate: '—',
    expiryDate: '—',
    source: 'Applicant',
    requirement: 'Required',
    availability: 'Missing',
    verification: 'Needs Verification',
    validity: 'Not Applicable',
    reuse: 'Service-specific',
    dependency: 'Available now',
    usedBy: [
      { dept: 'MPCB', service: 'Consent to Establish', requirement: 'Required' },
      { dept: 'DISH', service: 'Factory Registration', requirement: 'Required' },
    ],
    version: 0,
    description: 'Statutory declaration by the authorised signatory certifying that all information submitted in the application is true, correct, and complete.',
    whyRequired: 'A statutory declaration is required by law to establish legal accountability for information submitted in regulatory applications.',
    whatItContains: 'Declaration statement, applicant name, designation, entity name, date, and authorised signature.',
    grRule: null,
    grClause: null,
    grEffective: null,
    whereObtained: 'Generated as part of the EKATMA application submission process. Must be signed and uploaded before application submission.',
    versionHistory: [],
  },
  {
    id: 'DOC-008',
    name: 'Inspection Report (Pre-Operation)',
    category: 'Inspection-stage Documents',
    issueDate: '—',
    expiryDate: '—',
    source: 'MPCB / Department Inspector',
    requirement: 'Conditional',
    availability: 'Missing',
    verification: 'Needs Verification',
    validity: 'Not Applicable',
    reuse: 'Service-specific',
    dependency: 'Inspection-stage only',
    usedBy: [
      { dept: 'MPCB', service: 'Consent to Operate', requirement: 'Conditional' },
    ],
    version: 0,
    description: 'Site inspection report prepared by the designated MPCB inspector verifying that the constructed facility matches the approved application.',
    whyRequired: 'A site inspection is required before Consent to Operate is issued to confirm that the actual installation matches the approved plans.',
    whatItContains: 'Inspector observations, compliance status, deficiency remarks, inspection date, and inspector signature.',
    grRule: 'Maharashtra Prevention and Control of Pollution Rules',
    grClause: 'Rule 6 — Inspection prior to Consent to Operate',
    grEffective: '01 Jan 2000',
    whereObtained: 'Generated by the inspecting officer of MPCB. Not applicable until construction and installation are complete.',
    versionHistory: [],
    triggeringCondition: 'Required only at the Consent to Operate (CTO) stage after construction is complete.',
  },
  {
    id: 'DOC-INC-001',
    name: 'PSI 2019 Eligibility Certificate — EC-PSI-2026-01248',
    category: 'Incentives',
    issueDate: '04 Aug 2026',
    expiryDate: '03 Aug 2031',
    source: 'Industries, Energy & Labour Dept., GoM',
    requirement: 'Conditional',
    availability: 'Available',
    verification: 'Government-issued',
    validity: 'Valid',
    reuse: 'Reusable',
    dependency: 'Available now',
    usedBy: [
      { dept: 'Industries Dept.', service: 'PSI 2019 Capital Subsidy Claim', requirement: 'Required' },
      { dept: 'Industries Dept.', service: 'PSI 2019 Electricity Duty Exemption Claim', requirement: 'Required' },
      { dept: 'MSEDCL', service: 'Electricity Duty Exemption', requirement: 'Required' },
    ],
    version: 1,
    description: 'Eligibility Certificate issued by Industries, Energy & Labour Dept., GoM under Package Scheme of Incentives 2019, confirming eligibility for Capital Subsidy and Electricity Duty Exemption.',
    whyRequired: 'The Eligibility Certificate is the formal determination of incentive eligibility. It is required before periodic claims can be submitted to the administering authority.',
    whatItContains: 'Certificate ID, eligible benefits, eligible quantum per benefit, certificate validity, conditions, scheme reference, and business/project identification.',
    grRule: 'Package Scheme of Incentives 2019 — Government Resolution',
    grClause: 'Clause 7 — Eligibility Certificate',
    grEffective: '01 Apr 2019',
    whereObtained: 'Issued by the General Manager, District Industries Centre (DIC) / Industries Dept., GoM, upon approval of the Eligibility Application.',
    versionHistory: [
      { version: 1, uploaded: '04 Aug 2026', verification: 'Government-issued' },
    ],
    extractedData: {
      fields: [
        { label: 'Scheme Reference', value: 'Package Scheme of Incentives (PSI) 2019', match: true },
        { label: 'Zone Classification', value: 'Zone ‘D’ — High Priority Region', match: true },
        { label: 'Max Subsidy Quantum', value: '₹21.82 Crores (45% of Eligible FCI)', match: true },
        { label: 'Electricity Exemption', value: '100% Exemption for 7 Years', match: true },
      ],
      verificationState: 'Government-issued (DIC Directorate)',
      reviewRequired: false,
      summary: 'Statutory incentive entitlement ratified by Directorate of Industries.',
    },
    certificateData: {
      certNumber: 'EC-PSI-2019-2026-01248',
      authority: 'Industries, Energy & Labour Department, Government of Maharashtra',
      issueDate: '04 Aug 2026',
      validUntil: '03 Aug 2031',
      signatoryName: 'Smt. S. P. Kulkarni, IAS',
      designation: 'General Manager, District Industries Centre (DIC) Thane',
      qrPayload: 'https://industries.maharashtra.gov.in/psi2019/verify?ec=EC-PSI-2019-2026-01248',
      conditions: [
        'Eligible for Capital Investment Subsidy up to 45% of gross eligible fixed capital investment.',
        '100% Electricity Duty Exemption for a period of 7 years from commercial production.',
        'Enterprise must maintain minimum direct employment of 120 persons.',
      ],
    },
  },
  {
    id: 'DOC-INC-002',
    name: 'CA-certified Fixed Capital Investment Statement',
    category: 'Incentives',
    issueDate: '05 Apr 2027',
    expiryDate: '—',
    source: 'Chartered Accountant',
    requirement: 'Conditional',
    availability: 'Available',
    verification: 'Needs Verification',
    validity: 'Valid',
    reuse: 'Service-specific',
    dependency: 'Available now',
    usedBy: [
      { dept: 'Industries Dept.', service: 'PSI 2019 Capital Subsidy Claim CLM-2027-001', requirement: 'Required' },
    ],
    version: 1,
    description: 'Chartered Accountant certified statement of fixed capital investment, itemised by land, building, plant and machinery, and other eligible assets.',
    whyRequired: 'Required to substantiate the capital subsidy claim quantum under PSI 2019. The administering authority verifies actual eligible investment against declared figures.',
    whatItContains: 'Itemised fixed capital investment schedule, CA certification, date, registration number.',
    grRule: 'Package Scheme of Incentives 2019',
    grClause: 'Claim Schedule — Capital Subsidy',
    grEffective: '01 Apr 2019',
    whereObtained: 'Obtained from the Chartered Accountant engaged by the business.',
    versionHistory: [
      { version: 1, uploaded: '12 Apr 2027', verification: 'Needs Verification' },
    ],
  },
  {
    id: 'DOC-INC-003',
    name: 'Commencement of Production Certificate',
    category: 'Incentives',
    issueDate: '18 Jul 2026',
    expiryDate: '—',
    source: 'Applicant / MIDC',
    requirement: 'Conditional',
    availability: 'Available',
    verification: 'Needs Verification',
    validity: 'Valid',
    reuse: 'Reusable',
    dependency: 'Available now',
    usedBy: [
      { dept: 'Industries Dept.', service: 'PSI 2019 Capital Subsidy Claim', requirement: 'Required' },
      { dept: 'MSEDCL', service: 'PSI 2019 Electricity Duty Exemption Claim', requirement: 'Required' },
    ],
    version: 1,
    description: 'Certificate confirming the date of commencement of commercial production at the industrial unit. Used to establish the claim eligibility period for incentive benefits.',
    whyRequired: 'Required to determine the start date of eligible periods for electricity duty exemption and milestone-based capital subsidy claims.',
    whatItContains: 'Commercial production commencement date, unit location, authorised signatory declaration.',
    grRule: 'Package Scheme of Incentives 2019',
    grClause: 'Clause 4 — Commencement of Production',
    grEffective: '01 Apr 2019',
    whereObtained: 'Self-declared and submitted with the Eligibility Application. May require MIDC / DIC countersignature.',
    versionHistory: [
      { version: 1, uploaded: '18 Jul 2026', verification: 'Needs Verification' },
    ],
    certificateData: {
      certNumber: 'MIDC/PROD/COMM/2026/089',
      authority: 'Joint Inspection Committee — MIDC & DIC Thane',
      issueDate: '18 Jul 2026',
      validUntil: 'Permanent Record',
      signatoryName: 'Shri A. D. Patil',
      designation: 'Joint Director of Industries, Konkan Division',
      qrPayload: 'https://maitri.mahaonline.gov.in/verify/production?id=MIDC-PROD-COMM-2026-089',
      conditions: [
        'Commercial production commenced on 15 Jul 2026.',
        'Initial manufacturing lines operational for bulk formulation.',
      ],
    },
  },
] as const;

export const E11_DOC_CATEGORIES = [
  'All',
  'Business',
  'Promoter',
  'Land',
  'Project',
  'Technical',
  'Building',
  'Environmental',
  'Safety',
  'Previous Approvals',
  'Professional Certificates',
  'Declarations',
  'Inspection-stage Documents',
  'Incentives',
  'Other',
] as const;

export function findDocumentById(id: string): DocRecord | undefined {
  return EKATMA_DOCS.find(doc => doc.id === id);
}

export function findDocumentForBusiness(businessId: string, documentId: string): DocRecord | undefined {
  if (!findBusinessEntity('document', businessId, documentId)) return undefined;
  return findDocumentById(documentId);
}

export function listDocumentsForBusiness(businessId: string): DocRecord[] {
  return EKATMA_DOCS.filter(doc => Boolean(findBusinessEntity('document', businessId, doc.id)));
}

export function reqBadge(r: DocReqState) {
  const map: Record<DocReqState, string> = {
    Required: 'bg-[#fee2e2] text-[#b91c1c] border-[#fca5a5]',
    Conditional: 'bg-[#fdf8e6] text-[#7a5807] border-[#fae69e]',
    'Not Required': 'bg-[#F9FAF2] text-[#555C56] border-[#e3ebe1]',
  };
  return <span className={`inline-block px-1.5 py-0.5 rounded text-[10px] font-semibold border ${map[r]}`}>{r}</span>;
}

export function availBadge(a: DocAvailState) {
  const map: Record<DocAvailState, string> = {
    Available: 'bg-[#dcfce7] text-[#15803d] border-[#86efac]',
    Uploaded: 'bg-[#edf5ef] text-[#539160] border-[#a1cba9]',
    Processing: 'bg-[#fdf8e6] text-[#D4A017] border-[#fae69e]',
    Missing: 'bg-[#F9FAF2] text-[#9ab098] border-[#c8d4c7]',
  };
  return <span className={`inline-block px-1.5 py-0.5 rounded text-[10px] font-semibold border ${map[a]}`}>{a}</span>;
}

export function verifBadge(v: DocVerifState) {
  const map: Record<DocVerifState, string> = {
    'Department-verified': 'bg-[#dcfce7] text-[#166534] border-[#86efac]',
    'System-verified': 'bg-[#edf5ef] text-[#539160] border-[#a1cba9]',
    'User-confirmed': 'bg-[#ede9fe] text-[#6d28d9] border-[#c4b5fd]',
    'Self-declared': 'bg-[#F9FAF2] text-[#4A4A4A] border-[#c8d4c7]',
    'Needs Verification': 'bg-[#fdf8e6] text-[#7a5807] border-[#fae69e]',
    Invalid: 'bg-[#fee2e2] text-[#b91c1c] border-[#fca5a5]',
    'Government-issued': 'bg-[#dcfce7] text-[#166534] border-[#86efac]',
  };
  return <span className={`inline-block px-1.5 py-0.5 rounded text-[10px] font-semibold border ${map[v]}`}>{v}</span>;
}

export function validityBadge(v: DocValidity) {
  const map: Record<DocValidity, string> = {
    Valid: 'bg-[#dcfce7] text-[#15803d] border-[#86efac]',
    Expired: 'bg-[#fee2e2] text-[#b91c1c] border-[#fca5a5]',
    'Not Applicable': 'bg-[#F9FAF2] text-[#9ab098] border-[#e3ebe1]',
  };
  return <span className={`inline-block px-1.5 py-0.5 rounded text-[10px] font-semibold border ${map[v]}`}>{v}</span>;
}

export function reuseBadge(r: DocReuse) {
  return r === 'Reusable' ? (
    <span className="inline-block px-1.5 py-0.5 rounded text-[10px] font-semibold border bg-[#ede9fe] text-[#6d28d9] border-[#c4b5fd]">
      Reusable
    </span>
  ) : (
    <span className="inline-block px-1.5 py-0.5 rounded text-[10px] font-semibold border bg-[#F9FAF2] text-[#4A4A4A] border-[#c8d4c7]">
      Service-specific
    </span>
  );
}

export function depBadge(d: DocDependency) {
  const map: Record<DocDependency, string> = {
    'Available now': 'text-[#15803d]',
    'Generated by prerequisite approval': 'text-[#D4A017]',
    'Blocked until prerequisite': 'text-[#b91c1c]',
    'Inspection-stage only': 'text-[#6d28d9]',
    'Unlocks downstream services': 'text-[#15803d]',
  };
  return <span className={`text-[10px] font-medium ${map[d]}`}>{d}</span>;
}
